version: "3.9"
services:
  db:
    image: postgres:13.7
    container_name: db_pg
    mem_limit: 1536MB
    mem_reservation: 1G
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
    - "5442:5432"
    volumes:
    - ./db-data:/var/lib/postgresql/data
    - ./db-backup:/var/lib/postgresql/backup
    restart: always

  pgadmin:
    image: dpage/pgadmin4:6.10
    container_name: pgadmin_pg
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.ru
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8080:80"
    restart: always
    links:
    - db:pgsql-server
    volumes:
    - ./pgadmin-data:/var/lib/pgadmin