version: "3.9"
services:
  centos7:
    image: pycontribs/centos:7
    container_name: centos7
    entrypoint: "tail -f /dev/null"

  ubuntu:
    image: pycontribs/ubuntu
    container_name: ubuntu
    entrypoint: "tail -f /dev/null"
