Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
       config.vm.provider "virtualbox" do |v|
       v.memory = 4096
       v.cpus = 2
       v.name = "Ubuntu-20.04-Course-work"
       v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
       end
       config.vm.network "forwarded_port", id: "ssh_", host_ip: "192.168.0.5", guest: 22, host: 2222      
       config.vm.network "forwarded_port", id: "https", host_ip: "192.168.0.5", guest: 443, host: 1443
       config.vm.network "private_network", ip: "10.152.152.12", netmask: "255.255.192.0", virtualbox__intnet: "Whonix"
       config.vm.provision "shell", run: "always", inline: "ip route del default via 10.0.2.2 || true"
       config.vm.provision "shell", run: "always", inline: "ip route add default via 10.152.152.10 || true"
end
