version: "3.9"
services:
  db:
    image: mysql:8.0.29
    mem_limit: 1536MB
    mem_reservation: 1G
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
    - "3306:3306"
    volumes:
    - ./mysql_datadir:/var/lib/mysql
    restart: always
    
  adminer:
    image: adminer
    ports:
    - "8080:8080"
    restart: always